---
title: "p8105_hw6_si2426"
output: github_document
date: "2022-11-20"
---

```{r, include = FALSE}
library(tidyverse)
library(purrr)
library(epiDisplay)
```

## Problem 2

```{r}
homicide_df = read.csv("./data/homicide-data.csv") %>% 
  mutate(city_state = paste(city, state, sep = ", "), 
         solved = ifelse(disposition == "Closed by arrest", 1, 0), victim_age = as.numeric(victim_age), victim_race = fct_relevel(victim_race, "White")) %>%
  filter(city_state != "Dallas, TX", city_state != "Phoenix, AZ",
           city_state != "Kansas City, MO",
           city_state != "Tulsa, AL") %>%
  filter(victim_race ==  "White" | victim_race ==  "Black")
```

```{r}
baltimore_homicide = homicide_df %>% 
  filter(city == "Baltimore")

baltimore_logistic = 
  baltimore_homicide %>% 
  glm(solved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 

baltimore_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>%
  dplyr::select(term, log_OR = estimate, OR, p.value) %>% 
  knitr::kable(digits = 3)

confint(baltimore_logistic)
```

```{r, message = FALSE}
cities_logistic = homicide_df %>% 
  group_by(city_state) %>% 
  nest() %>%
  mutate( 
    models = map(data, ~glm(data = .x, solved ~ victim_age + victim_race + victim_sex, family = binomial())),
    result = map(models, broom::tidy)
    ) %>%
  dplyr:: select(-data, -models) %>% 
  unnest(result) %>%
  mutate(OR = exp(estimate)) %>%
  dplyr:: select(term, log_OR = estimate, OR, p.value)
```

```{r}
victim_sex_logistic = cities_logistic %>% 
  filter(term == "victim_sexMale") %>%
  ungroup(city_state) %>%
  mutate(city_state = fct_reorder(city_state, OR))

ggplot(victim_sex_logistic, aes(x = city_state, y = OR)) + 
  geom_point() +
  labs(x = "City, State", y = "Adjusted Odds Ratio") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 3

```{r}
birthweight_df = read.csv("./data/birthweight.csv") %>%
  mutate(babysex = as.factor(babysex),
         frace = as.factor(frace),
         malform = as.factor(malform),
         mfrace = as.factor(mrace))
```







